### ISSUE TITLE
Strange issue with gnome-terminal

### ISSUE THREAD

**Issue by agzam** [stumpwm/stumpwm#788]
I'm seeing strange bug that crashes stumpwm, interestingly, it only happens when I attempt to run gnome-terminal. Basically I have gnome-terminal in one of the frames and any attempt to create a split results in this.

![image](https://user-images.githubusercontent.com/1091022/82746867-4724f800-9d49-11ea-9058-602f8ab94a89.png)

Sorry for posting a picture, my attempts to collect the stacktrace weren't successful. copy-unhandled-error didn't work, and increasing *debug-level* and redirect-all-output into a file didn't work either.

I'm not so much bothered about the bug since it doesn't really affect other terminal apps (I think), but this might be an indication of some related stuff like xrandr issues.

**Comment by lxbarbosa** [comment]
Does the issue still happen?
Which version of StumpWM you are using?

What if you run StumpWM with no config still reproducing the issue?

I unsuccessfully could not reproduce your issue, using upstream custom build w/ or w/out config file.

**Comment by PuercoPop** [comment]
I can't reproduce either. But it sounds like an issue that was fixed a while ago.

https://github.com/stumpwm/stumpwm/commit/072836f261db2dc2b61ec91e4b43451e6a72d0ab

 @agzam What version of StumpWM does this happen in?

**Comment by brettgilio** [comment]
Also cant reproduce this.

**Comment by agzam** [comment]
My apologies , I got swamped with work and couldn't check this sooner.
I have updated things and now running Stump v`19.11-161-g060898c`
I was just about to say "It looks like it was fixed". Alas, I am still seeing this bug. It seems to be related to the way how Stump uses xrand settings. In my config I have added couple of functions that let me switch from a single desktop to a multi-monitor setup, when I do that, sometimes Stump throws errors similar to the screenshot above. Sometimes, it even dies completely, killing all the apps, and kicks me off to GDM. Utterly frustrating.

**Comment by PuercoPop** [comment]
Are the xrandr commands in question this ones? https://github.com/agzam/.stumpwm.d/blob/d1be555481b401ee2705b698d9afcadf2a51d9b0/xrandr.lisp

What are the specific steps to reproduce? If it doesn't involve multiple monitors I can take a look at it.

**Comment by agzam** [comment]
@PuercoPop I'm not exactly sure. In my case it simply takes running gnome-terminal and trying to get window splits. It doesn't even have to be running in the same frame. Running gnome-terminal and at the same time using xrandr to change display modes - on my config, it's a recipe for a crash.

**Comment by PuercoPop** [comment]
I think the issue may be related with gnome-terminal geometry-hints being for the previous screen resolution? Would it be possible to get more a gist of the log? You try running on the version on #796  to make the log collection process easier.
Plus can you add some extra logging information to maximize windows? Right before the call to change-property.
```lisp
      ;; update the "extents"
      (dformat "drawable-width: ~A. width: ~A. wx: ~A.~%" (xlib:drawable-width (window-parent win)) width wx)
```

As a palliative measure until we manage to get to the bottom of this you can wrap the width and height calculations on maximize-window with (max 0 _)`. That should prevent the crashing.

```diff
@@ -211,9 +211,9 @@ (defun maximize-window (win)
       ;; update the "extents"
       (xlib:change-property (window-xwin win) :_NET_FRAME_EXTENTS
                             (list wx
-                                  (- (xlib:drawable-width (window-parent win)) width wx)
+                                  (max 0 (- (xlib:drawable-width (window-parent win)) width wx))
                                   wy
-                                  (- (xlib:drawable-height (window-parent win)) height wy))
+                                  (max 0 (- (xlib:drawable-height (window-parent win)) height wy)))
                             :cardinal 32))
     (update-configuration win)))
```

**Comment by agzam** [comment]
I also have problems running xrandr commands, and I can't figure out what the heck. It throws stuff like this:

![20200724_225251](https://user-images.githubusercontent.com/1091022/88450076-22103c80-ce01-11ea-9809-e02b2aef406e.jpg)

For some reason `(xinerama:xinerama-is-active *display*)` returns `t`, is that right? `.local/share/xorg/Xorg.1.log` does not indicate that it is active.

**Comment by PuercoPop** [comment]
@agzam The last error you encounter is this bug: https://github.com/stumpwm/stumpwm/issues/763

It is possible that we need add some handlers to xrandr events like `RROutputChangeNotify`
